// SPDX-License-Identifier: Apache-2.0

import Foundation

@main
struct SimUseNetworkBuildInfoTool {
  static func main() throws {
    let options = try BuildInfoToolOptions.parse(arguments: CommandLine.arguments)
    let outputURL = URL(filePath: options.outputPath)
    let version = try BuildInfoVersionResolver.resolve(
      environmentVersion: options.environmentVersion
    )
    let source = BuildInfoVersionResolver.generatedSource(version: version)

    try FileManager.default.createDirectory(
      at: outputURL.deletingLastPathComponent(),
      withIntermediateDirectories: true
    )
    if let existingSource = try? String(contentsOf: outputURL, encoding: .utf8),
      existingSource == source
    {
      return
    }
    try source.write(to: outputURL, atomically: true, encoding: .utf8)
  }
}

struct BuildInfoToolOptions {
  let outputPath: String
  let environmentVersion: String?

  static func parse(arguments: [String]) throws -> Self {
    var outputPath: String?
    var environmentVersion: String?
    var index = 1

    while index < arguments.count {
      switch arguments[index] {
      case "--output":
        outputPath = try value(after: index, in: arguments)
        index += 2
      case "--environment-version":
        environmentVersion = try value(after: index, in: arguments)
        index += 2
      default:
        throw BuildInfoToolError.message("Unknown option: \(arguments[index])")
      }
    }

    guard let outputPath else {
      throw BuildInfoToolError.message("--output is required")
    }
    return Self(
      outputPath: outputPath,
      environmentVersion: environmentVersion
    )
  }

  private static func value(after index: Int, in arguments: [String]) throws -> String {
    guard index + 1 < arguments.count else {
      throw BuildInfoToolError.message("\(arguments[index]) requires a value")
    }
    return arguments[index + 1]
  }
}

enum BuildInfoVersionResolver {
  static func resolve(environmentVersion: String?) throws -> String {
    guard let environmentVersion else { return "dev" }
    guard let version = normalized(environmentVersion) else {
      throw BuildInfoToolError.message(
        "SIM_USE_NETWORK_BUILD_VERSION must not be empty"
      )
    }
    return version
  }

  static func generatedSource(version: String) -> String {
    """
    // SPDX-License-Identifier: Apache-2.0
    // Generated by SimUseNetworkBuildInfoTool. Do not edit.

    enum SimUseNetworkBuildInfo {
      static let version = \(String(reflecting: version))
    }

    """
  }

  private static func normalized(_ value: String) -> String? {
    let value = value.trimmingCharacters(in: .whitespacesAndNewlines)
    guard !value.isEmpty else { return nil }
    if value.first == "v", value.dropFirst().first?.isNumber == true {
      return String(value.dropFirst())
    }
    return value
  }
}

enum BuildInfoToolError: Error, CustomStringConvertible {
  case message(String)

  var description: String {
    switch self {
    case .message(let message): message
    }
  }
}
